#!/bin/bash

### BEGIN INIT INFO
# Provides:          flyzy2005.com
# Required-Start:    $network $syslog
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: shadowsocks control
# Description:       shadowsocks control
### END INIT INFO
NAME=Shadowsocks
if [ -f /usr/bin/ssserver ]; then
    DAEMON=/usr/bin/ssserver
elif [ -f /usr/local/bin/ssserver ]; then
    DAEMON=/usr/local/bin/ssserver
fi
CONF=/etc/shadowsocks.json
RETVAL=0

check_running(){
    PID=$(ps -ef | grep -v grep | grep -i "${DAEMON}" | awk '{print $2}')
    if [ -n "$PID" ]; then
        return 0
    else
        return 1
    fi
}

do_start(){
    check_running
    if [ $? -eq 0 ]; then
        echo "$NAME (pid $PID)Running"
        exit 0
    else
        $DAEMON -c $CONF -d start
        RETVAL=$?
        if [ $RETVAL -eq 0 ]; then
            echo "$NAMEStartUp"
        else
            echo "$NAMEFaild，check log file"
        fi
    fi
}

do_stop(){
    check_running
    if [ $? -eq 0 ]; then
        $DAEMON -c $CONF -d stop
        RETVAL=$?
        if [ $RETVAL -eq 0 ]; then
            echo "$NAMEStop"
        else
            echo "$NAMEFail，check log file"
        fi
    else
        echo "$NAMEStopped"
        RETVAL=1
    fi
}

do_status(){
    check_running
    if [ $? -eq 0 ]; then
        echo "$NAME (pid $PID)Running"
    else
        echo "$NAMEinactive。RUN/etc/init.d/ss-fly start start ss"
        RETVAL=1
    fi
}

do_restart(){
    do_stop
    sleep 0.5
    do_start
}

case "$1" in
    start|stop|restart|status)
    do_$1
    ;;
    *)
    echo "Usage: $0 { start | stop | restart | status }"
    RETVAL=1
    ;;
esac

exit $RETVAL
